# Generated by Django 4.1 on 2022-08-16 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_centre', '0002_remove_post_order_post_categories_post_content_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='published',
            field=models.BooleanField(default=False),
        ),
    ]
