# Generated by Django 4.1 on 2022-08-16 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_centre', '0003_post_published'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='order',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
