# Generated by Django 4.1 on 2022-08-16 17:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog_centre', '0004_post_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='order',
        ),
    ]
